apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: stuebencountysurvey-online-tls
spec:
  secretName: stuebencountysurvey-online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: stuebencountysurvey.online
  dnsNames:
    - stuebencountysurvey.online
    - www.stuebencountysurvey.online
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - stuebencountysurvey.online
          - www.stuebencountysurvey.online
